# Set by expo-router. This enables Fabric-only features from react-native-screens
ENV['RNS_GAMMA_ENABLED'] ||= '1'
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
require 'fileutils'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']

  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true'
ENV['RCT_HERMES_V1_ENABLED'] ||= '1' if podfile_properties['expo.useHermesV1'] == 'true'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'Tothemoon' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    # codex-ios-26-fmt-fix start
    installer.pods_project.targets.each do |target|
      next unless target.name == 'fmt'

      target.build_configurations.each do |build_configuration|
        definitions = build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        definitions = [definitions] unless definitions.is_a?(Array)
        definitions << 'FMT_USE_CONSTEVAL=0' unless definitions.include?('FMT_USE_CONSTEVAL=0')
        build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions

        cxx_flags = build_configuration.build_settings['OTHER_CPLUSPLUSFLAGS'] || ['$(inherited)']
        cxx_flags = [cxx_flags] unless cxx_flags.is_a?(Array)
        cxx_flags << '-DFMT_USE_CONSTEVAL=0' unless cxx_flags.include?('-DFMT_USE_CONSTEVAL=0')
        build_configuration.build_settings['OTHER_CPLUSPLUSFLAGS'] = cxx_flags
      end
    end

    fmt_base_header = File.join(installer.sandbox.root.to_s, 'fmt/include/fmt/base.h')
    if File.exist?(fmt_base_header)
      contents = File.read(fmt_base_header)
      apple_clause = <<~RUBY.chomp
        #elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L
        #  define FMT_USE_CONSTEVAL 0  // consteval is broken in Apple clang < 14.
      RUBY
      patched_clause = <<~RUBY.chomp
        #elif defined(__apple_build_version__)
        #  define FMT_USE_CONSTEVAL 0  // Disabled for Apple toolchains due to newer SDK compile regressions.
      RUBY

      if contents.include?(apple_clause) && !contents.include?(patched_clause)
        FileUtils.chmod('u+w', fmt_base_header)
        File.write(fmt_base_header, contents.sub(apple_clause, patched_clause))
      end
    end
    # codex-ios-26-fmt-fix end
  end
end


# >>> Inserted by react-native-widget-extension

target 'TothemoonWidgets' do
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
end

# >>> Inserted by react-native-widget-extension